### ISSUE TITLE
无法获取制定集群配置更新

### ISSUE THREAD

**Issue by shaukei** [fengzhibin/apollo-sdk-config#2]
client.php，line 412

`        return sprintf(
            '%s/notifications/v2?appId=%s&cluster=%s&notifications=%s',
            $this->configServerUrl,
            $appId,
            $this->clusterName,
            $notifications
        );`

**Comment by fengzhibin** [comment]
> client.php，line 412
> 
> ` return sprintf( '%s/notifications/v2?appId=%s&cluster=%s&notifications=%s', $this->configServerUrl, $appId, $this->clusterName, $notifications );`

什么问题没太看懂，你详细描述一下使用场景

**Comment by fengzhibin** [comment]
> client.php，line 412
> 
> ` return sprintf( '%s/notifications/v2?appId=%s&cluster=%s&notifications=%s', $this->configServerUrl, $appId, $this->clusterName, $notifications );`

已在1.0.5版本修复该问题，https://github.com/fengzhibin/apollo-sdk-config/releases/tag/1.0.5

**Comment by shaukei** [comment]
> > client.php，line 412
> > ` return sprintf( '%s/notifications/v2?appId=%s&cluster=%s&notifications=%s', $this->configServerUrl, $appId, $this->clusterName, $notifications );`
> 
> 已在1.0.5版本修复该问题，https://github.com/fengzhibin/apollo-sdk-config/releases/tag/1.0.5

谢谢！

**Comment by flylan** [comment]
问题已解决
