### ISSUE TITLE
怎么设置环境变量？

### ISSUE THREAD

**Issue by tcsp** [fengzhibin/apollo-sdk-config#5]
![image](https://user-images.githubusercontent.com/10058952/141718411-9402b009-5038-4c52-ab40-d4912507c36c.png)
一般还需要区分下环境变量，没有找到对应的入参

**Comment by flylan** [comment]
阿波罗的接口好像没有区分环境的

**Comment by flylan** [comment]
参考以下两个链接:
https://www.apolloconfig.com/#/zh/usage/other-language-client-user-guide
https://github.com/apolloconfig/apollo/issues/2511

阿波罗第三方接口没有环境参数传入，实际上阿波罗面板上面显示的环境列表，需要在阿波罗系统上面配置执行不同的config_server_url的，
例如
DEV -> dev.apolloconfig.com
PRO -> pro.apolloconfig.com

因此如果需要区分不同的环境，初始化不同的client就行。例如

初始化测试环境阿波罗
$devApolloClient = new \ApolloSdk\Config\Client(['config_server_url' => 'dev.apolloconfig.com']);

初始化正式环境阿波罗
$proApolloClient = new \ApolloSdk\Config\Client(['config_server_url' => 'pro.apolloconfig.com']);

而你截图的那个那个环境参数列表实际只对于阿波罗面板有用，给用户查看不同的阿波罗中心的数据。环境参数对于阿波罗接入端没有什么用途
